version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
    private-ethereum:
        image: ethereum/client-go:v1.9.0
        container_name: "private-ethereum"
        volumes:
            - ./node:/root/.ethereum/
            - ./embed/geth/files/genesis.json:/root/genesis.json:ro
            - ./embed/geth/files/keystore:/root/.ethereum/keystore:rw
        command: --identity "private-ethereum" --nodiscover --maxpeers 0 --verbosity 3 --networkid=45 init /root/genesis.json

