version: '3.5'

services:
  # mysql:
  #   image: mysql:5.7.23
  #   container_name: mysql
  #   ports:
  #     - 3306:3306
  #   expose:
  #     - 3306
  #   volumes:
  #     - ./embed/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
  #     - ./embed/mysql/data:/var/lib/mysql/:rw
  #   restart: always
  #   networks:
  #     - backend
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "qwe123!"

  # redis:
  #   image: redis:5.0.3-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./embed/redis/redis.conf:/etc/redis.conf:ro
  #     - ./embed/redis/data:/data/:rw
  #   restart: always
  #   entrypoint: ["redis-server", "/etc/redis.conf"]
  #   networks:
  #     - backend

  # api:
  #   container_name: ethApi
  #   build:
  #     context: ./api
  #     dockerfile: DockerfileDev
  #   ports:
  #     - 80:10230 #10230 10230 맵핑
  #   environment:
  #     - NODE_ENV=dev
  #   volumes:
  #     - ethApi:/data/ethApi
  #   networks:
  #     - backend
  #   depends_on:
  #     - noti

  # noti:
  #   container_name: ethNoti
  #   build:
  #     context: ./noti
  #     dockerfile: DockerfileDev
  #   environment:
  #     - NODE_ENV=dev
  #   volumes:
  #     - ethNoti:/data/ethNoti
  #   networks:
  #     - backend
  #   depends_on: 
  #     - private-ethereum

  private-ethereum:
    image: ethereum/client-go:v1.9.0
    container_name: "private-ethereum"
    volumes:
        - ./node:/root/.ethereum/
        - ./embed/geth/files/genesis.json:/root/genesis.json:ro
        - ./embed/geth/files/keystore:/root/.ethereum/keystore:rw
        - ./embed/geth/files/automining.js:/root/automining.js:ro
    ports:
        - "30303:30303"
        - "30303:30303/udp"
        - "8545:8545"
        - "8546:8546"
    command: --identity "private-ethereum" --rpc --rpcaddr "0.0.0.0" --rpcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --ws --wsaddr "0.0.0.0" --nodiscover --maxpeers 0 --verbosity 3 --rpccorsdomain='*' --networkid=45 --allow-insecure-unlock --mine --minerthreads=1 --miner.gastarget 21000 --miner.gaslimit 21000 --miner.gasprice 8000000000
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  ethNoti:
  ethApi: